name: 'The named action'
description: "Does a useful thing"
inputs:
  base64_workload_identity_provider:
    description: GCP Workload Identity Pool Provider ID (e.g. projects/<project-number>/locations/global/workloadIdentityPools/<pool>/providers/<id>)
    required: true
  base64_gcp_service_account:
    description: GCP service Ac
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Base64 decode params and set as env vars
      shell: bash
      run: |
        echo "WORKLOAD_IDENTITY_PROVIDER=$(echo -n ${{ inputs.base64_workload_identity_provider}} | base64 -d)" >> $GITHUB_ENV
        echo "GCP_SERVICE_ACCOUNT=$(echo -n ${{ inputs.base64_gcp_service_account}} | base64 -d)" >> $GITHUB_ENV
    - name: Workload Identity Auth
      id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
    - name: Debug gcloud auth
      shell: bash
      run: gcloud auth list
