name: 'Authenticate to Google Cloud'
description: 'Authenticate to Google Cloud with GitHub Actions OIDC tokens and Workload Identity Federation and setup gcloud'
inputs:
  workload_identity_provider:
    description: GCP Workload Identity Pool Provider ID (e.g. projects/<project-number>/locations/global/workloadIdentityPools/<pool>/providers/<id>)
    required: true
  gcp_service_account:
    description: GCP service Account
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ inputs.base64_workload_identity_provider}}
        service_account: ${{ inputs.base64_gcp_service_account }}
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1
    - name: Debug gcloud auth
      shell: bash
      run: gcloud auth list
