name: Publish GitHub Action

on:
  push:
    branches:
      - "main"

jobs:
  release:
    uses: vivantehealth/github-actions-workflows/.github/workflows/semver-release.yml@main
    with:
      default-bump: patch
