name: Publish GitHub Action

on:
  push:
    branches:
      - "tmp"

jobs:
  deploy-uat:
    uses: vivantehealth/github-actions-workflows/.github/workflows/tf-deploy.yml@tf-deploy
    with:
      env: uat
    secrets:
      base64-gcp-service-account: ${{ secrets.BASE64_GCP_SERVICE_ACCOUNT }}
