name: Publish GitHub Action

on:
  push:
    branches:
      - "tmp"

jobs:
  deploy-uat:
    with:
      env: uat
    secrets:
      base64-gcp-service-account: ${{ secrets.BASE64_GCP_SERVICE_ACCOUNT }}
